# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

---
- name: Host | Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Host | Ensure hostname is in /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}.+$"
    line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ hostname }}"

- name: Host | Disable at runtime
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Host | Swap disable on boot
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap

- name: Host | Install Kernel packages (Ubuntu)
  when: ansible_architecture == 'arm64'
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - linux-modules-extra-raspi

- name: Host | Activating cgroup support (Debian)
  when: ansible_distribution == 'Debian'
  ansible.builtin.lineinfile:
    path: /boot/cmdline.txt
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  notify: reboot

# - name: Host | Activating cgroup support (Ubuntu)
#   when: ansible_distribution == 'Ubuntu'
#   ansible.builtin.lineinfile:
#     path: /boot/firmware/cmdline.txt
#     regexp: '^((?!.*\bcgroup_enable=memory cgroup_memory=1\b).*)$'
#     line: '\1 cgroup_enable=memory cgroup_memory=1'
#     backrefs: true
#   notify: reboot
